apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-app
#  namespace: default
  labels:
    app: dice
spec:
  selector:
    matchLabels:
      app: dice
  replicas: 1
  template:
    metadata:
      labels:
        app: dice
    spec:
      containers:
        - name: dice
          image: +REPO+/dice-app:1
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: dice-app
spec:
  selector:
    app: dice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
